#theme: jekyll-theme-cayman
#theme: jekyll-theme-minimal
remote_theme: zendesk/jekyll-theme-zendesk-garden@main
title: Matthew Barclay
#description: Bookmark this to keep an eye on my project updates!
sidebar:
 - home
 - about
 - label: Projects
   children:
   - wine
   - adoptions
   - parking
 - contact
version: false
linkedin_badge: |
  <script src="https://platform.linkedin.com/badges/js/profile.js" async defer type="text/javascript"></script>
  <div class="badge-base LI-profile-badge" data-locale="en_US" data-size="medium" data-theme="light" data-type="VERTICAL" data-vanity="mattbarclay99" data-version="v1"></div>
              
